#!/usr/bin/env sh

# このスクリプトの場所に移動
SCRIPT_DIR=$(cd $(dirname $(readlink -f $0 || echo $0));pwd -P)
cd ${SCRIPT_DIR}

env=$NODE_ENV
echo 'push to' $env

cp .clasp.${env}.json .clasp.json
clasp push

rm -f .clasp.json
